"use client";
import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { Pencil, Star, Trash2, X } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { db, isoNow } from "@/lib/db";
import { CARD_TYPE_LABELS, ERROR_LABELS, SUBJECT_LABELS, type Card, type CardType, type ErrorReason, type Subject } from "@/lib/types";

export default function CardsPage(){const [subject,setSubject]=useState<Subject|"">("");const [reason,setReason]=useState<ErrorReason|"">("");const [tag,setTag]=useState("");const [editing,setEditing]=useState<Card>();const cards=useLiveQuery(()=>db.cards.orderBy("updatedAt").reverse().toArray(),[])??[];const shown=cards.filter((c)=>(!subject||c.subject===subject)&&(!reason||c.sourceReason===reason)&&(!tag||c.tags.some((t)=>t.includes(tag))));return <><PageHeader eyebrow="Memory cards" title="カード"/><div className="card grid-2" style={{marginBottom:12}}><select className="select" value={subject} onChange={(e)=>setSubject(e.target.value as Subject|"")}><option value="">全科目</option>{Object.entries(SUBJECT_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select className="select" value={reason} onChange={(e)=>setReason(e.target.value as ErrorReason|"")}><option value="">全A〜F由来</option>{Object.keys(ERROR_LABELS).map((v)=><option value={v} key={v}>{v}由来</option>)}</select><input className="input" style={{gridColumn:"1 / -1"}} placeholder="タグ検索" value={tag} onChange={(e)=>setTag(e.target.value)}/></div><div className="stack">{shown.map((card)=><article className="card" key={card.id}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><span className="pill">{CARD_TYPE_LABELS[card.cardType]}{card.sourceReason?`・${card.sourceReason}由来`:""}</span>{card.isImportant&&<Star size={18} fill="#e3a62f" color="#e3a62f"/>}</div><h2 style={{marginTop:14}}>{card.front}</h2><p className="muted" style={{whiteSpace:"pre-wrap"}}>{card.back}</p><div className="tiny muted">{SUBJECT_LABELS[card.subject]} ・ {card.tags.join(" / ")||"タグなし"}</div><div className="grid-2" style={{marginTop:12}}><button className="button secondary" onClick={()=>setEditing(card)}><Pencil size={16}/>編集</button><button className="button danger" onClick={async()=>{if(confirm("このカードを削除しますか？")){await db.transaction("rw",db.cards,db.reviewSchedules,async()=>{await db.cards.delete(card.id);await db.reviewSchedules.delete(`card:${card.id}`)})}}}><Trash2 size={16}/>削除</button></div></article>)}{!shown.length&&<div className="card muted">カードがありません。演習画面から作成できます。</div>}</div>{editing&&<EditCard card={editing} close={()=>setEditing(undefined)}/>}</>}
function EditCard({card,close}:{card:Card;close:()=>void}){const [front,setFront]=useState(card.front),[back,setBack]=useState(card.back),[type,setType]=useState<CardType>(card.cardType),[tags,setTags]=useState(card.tags.join(", ")),[important,setImportant]=useState(card.isImportant);async function save(){await db.cards.update(card.id,{front:front.trim(),back:back.trim(),cardType:type,tags:tags.split(",").map((x)=>x.trim()).filter(Boolean),isImportant:important,updatedAt:isoNow()});close()}return <div className="modal-backdrop"><div className="modal stack"><div style={{display:"flex",justifyContent:"space-between"}}><h2>カードを編集</h2><button className="button ghost" onClick={close}><X size={18}/></button></div><select className="select" value={type} onChange={(e)=>setType(e.target.value as CardType)}>{Object.entries(CARD_TYPE_LABELS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input className="input" value={front} onChange={(e)=>setFront(e.target.value)}/><textarea className="textarea" value={back} onChange={(e)=>setBack(e.target.value)}/><input className="input" value={tags} onChange={(e)=>setTags(e.target.value)}/><label className="choice"><input type="checkbox" checked={important} onChange={(e)=>setImportant(e.target.checked)}/>重要フラグとして扱う</label><button className="button" disabled={!front.trim()||!back.trim()} onClick={save}>保存</button></div></div>}
