"use client";
import { useRef, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { DatabaseBackup, Download, HardDrive, Trash2, Upload } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { createBackup, downloadFile, markBackupComplete, parseBackup, restoreBackup, type ParsedBackup } from "@/lib/backup";
import { db, setSetting } from "@/lib/db";

export default function SettingsPage(){
  const settings=useLiveQuery(async()=>({exam:await db.settings.get("examDate"),last:await db.settings.get("lastBackupAt")}),[]); const [exam,setExam]=useState<string>();const examValue=exam??(typeof settings?.exam?.value==="string"?settings.exam.value:"");const [backup,setBackup]=useState<ParsedBackup>();const [message,setMessage]=useState("");const fileRef=useRef<HTMLInputElement>(null);
  async function exportAll(){if(!confirm("問題文・画像・PDFを含むZIPをこの端末へ保存します。個人利用の範囲で安全に管理してください。"))return;const data=await createBackup();downloadFile(data,`medical-info-dojo-${new Date().toISOString().slice(0,10)}.backup.zip`);await markBackupComplete();setMessage("バックアップを保存しました")}
  async function read(file?:File){if(!file)return;try{const value=await parseBackup(await file.arrayBuffer());setBackup(value);setMessage("")}catch(e){setBackup(undefined);setMessage(e instanceof Error?e.message:"読み込めませんでした")}}
  async function restore(){if(!backup||!confirm("現在の全データを置き換えます。この操作は取り消せません。続けますか？"))return;await restoreBackup(backup);setBackup(undefined);setMessage("バックアップを復元しました")}
  async function persist(){if(!navigator.storage?.persist){setMessage("このブラウザは永続ストレージ要求に対応していません");return}const ok=await navigator.storage.persist();await setSetting("storagePersisted",ok);setMessage(ok?"永続ストレージが許可されました":"許可されませんでした。定期的にバックアップしてください")}
  async function wipe(){if(!confirm("問題、履歴、カード、設定をすべて削除しますか？")||!confirm("本当に削除しますか？バックアップがない場合は復元できません。"))return;await db.delete();await db.open();setMessage("ローカルデータをすべて削除しました")}
  return <><PageHeader eyebrow="Local only" title="設定"/><section className="card stack" style={{marginBottom:12}}><h2>試験日</h2><input type="date" className="input" value={examValue} onChange={(e)=>setExam(e.target.value)}/><button className="button" onClick={async()=>{await setSetting("examDate",examValue);setMessage("試験日を保存しました")}}>保存</button></section><section className="card stack" style={{marginBottom:12}}><h2><DatabaseBackup size={18}/> 完全バックアップ</h2><p className="muted tiny">最終保存: {typeof settings?.last?.value==="string"?new Date(settings.last.value).toLocaleString("ja-JP"):"未実施"}</p><button className="button" onClick={exportAll}><Download size={18}/>画像込みZIPを書き出す</button><button className="button secondary" onClick={()=>fileRef.current?.click()}><Upload size={18}/>バックアップZIPを選択</button><input ref={fileRef} type="file" accept=".zip,application/zip" hidden onChange={(e)=>read(e.target.files?.[0])}/>{backup&&<div className="notice">{backup.backup.exportedAt.slice(0,10)} のバックアップ：問題 {backup.backup.data.questions.length}問、メディア {backup.backup.data.media.length}件、履歴 {backup.backup.data.attempts.length}件、カード {backup.backup.data.cards.length}枚<button className="button danger" style={{width:"100%",marginTop:10}} onClick={restore}>現在のデータを置換して復元</button></div>}</section><section className="card stack" style={{marginBottom:12}}><h2><HardDrive size={18}/> ストレージ保護</h2><p className="muted tiny">ブラウザによる自動削除を避けるよう、この端末へ要求します。保証ではないためバックアップも併用してください。</p><button className="button secondary" onClick={persist}>永続ストレージを要求</button></section><section className="card stack"><h2>権利とデータ</h2><p className="muted tiny">本アプリは個人学習専用です。問題データを公開・共有・再配布しないでください。アプリは分析サービスや外部APIへデータを送信しません。</p><button className="button danger" onClick={wipe}><Trash2 size={18}/>全ローカルデータを削除</button></section>{message&&<p className={message.includes("ません")||message.includes("対応")?"error":"success"}>{message}</p>}</>;
}
