"use client";
import { useLiveQuery } from "dexie-react-hooks";
import { PageHeader } from "@/components/PageHeader";
import { db } from "@/lib/db";
import { isUnknownAnswer } from "@/lib/answerSelection";
import { ERROR_LABELS, SUBJECT_LABELS, type ErrorReason, type Subject } from "@/lib/types";

export default function DashboardPage(){
  const d=useLiveQuery(async()=>{const [questions,attempts,analyses,schedules]=await Promise.all([db.questions.toArray(),db.attempts.toArray(),db.errorAnalyses.toArray(),db.reviewSchedules.toArray()]);const latestYears=[...new Set(questions.map((q)=>q.examYear))].sort((a,b)=>b-a).slice(0,5);const target=questions.filter((q)=>latestYears.includes(q.examYear));const answered=new Set(attempts.map((a)=>a.questionId));const subject=(Object.keys(SUBJECT_LABELS) as Subject[]).map((key)=>{const ids=new Set(questions.filter((q)=>q.subject===key).map((q)=>q.id));const x=attempts.filter((a)=>ids.has(a.questionId));return {key,total:x.length,correct:x.filter((a)=>a.isCorrect).length}});const yearly=latestYears.map((year)=>{const ids=new Set(questions.filter((q)=>q.examYear===year).map((q)=>q.id));const x=attempts.filter((a)=>ids.has(a.questionId));return {year,total:x.length,correct:x.filter((a)=>a.isCorrect).length}});const reasons=(Object.keys(ERROR_LABELS) as ErrorReason[]).map((key)=>({key,count:analyses.filter((a)=>a.primaryReason===key).length}));const system=questions.filter((q)=>q.subject==="system").map((q)=>{const x=attempts.filter((a)=>a.questionId===q.id);const overdue=schedules.some((s)=>s.targetId===q.id&&s.dueAt<=new Date().toISOString());return {q,score:x.filter((a)=>!a.isCorrect).length*3+x.filter((a)=>isUnknownAnswer(a.userAnswer)).length+(overdue?1:0)}}).filter((x)=>x.score).sort((a,b)=>b.score-a.score).slice(0,5);return {progress:target.length?Math.round(target.filter((q)=>answered.has(q.id)).length/target.length*100):0,subject,yearly,reasons,system,attempts}} ,[]) ?? {progress:0,subject:[],yearly:[],reasons:[],system:[],attempts:[]};
  return <><PageHeader eyebrow="Learning analytics" title="弱点を見つける"/><section className="card" style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between"}}><h2>直近5年の進捗</h2><b>{d.progress}%</b></div><div className="progress"><i style={{width:`${d.progress}%`}}/></div></section><section className="card" style={{marginBottom:12}}><h2>科目別正答率</h2>{d.subject.map((s)=>{const rate=s.total?Math.round(s.correct/s.total*100):0;return <div key={s.key} style={{marginTop:14}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{SUBJECT_LABELS[s.key]}</span><b>{rate}%</b></div><div className="progress" style={{marginTop:5}}><i style={{width:`${rate}%`}}/></div></div>})}</section><section className="card" style={{marginBottom:12}}><h2>年度別正答率</h2>{d.yearly.map((y)=>{const rate=y.total?Math.round(y.correct/y.total*100):0;return <div className="list-row" key={y.year}><span>{y.year}年</span><b>{rate}% <span className="muted tiny">({y.total}回)</span></b></div>})}{!d.yearly.length&&<p className="muted">問題がありません。</p>}</section><section className="card" style={{marginBottom:12}}><h2>A〜F 誤答原因</h2>{d.reasons.map((r)=><div className="list-row tiny" key={r.key}><span><b>{r.key}</b> {ERROR_LABELS[r.key]}</span><b>{r.count}</b></div>)}</section><section className="card"><h2>システム系・要注意問題</h2>{d.system.map(({q,score})=><div className="list-row" key={q.id}><div><b>{q.examYear}年 問{q.questionNo}</b><div className="muted tiny">{q.topicSummary||"論点未設定"}</div></div><span className="pill">弱点 {score}</span></div>)}{!d.system.length&&<p className="muted">演習データがたまると表示されます。</p>}</section></>;
}
